micronaut:
  application:
    name: productstore
  server:
    port: 8010
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256
datasources:
  default:
    url: jdbc:sqlite:db/productMiral.db
    driverClassName: org.sqlite.JDBC
    #username: sa
    #password: ''
    #schema-generate: CREATE_DROP
    #dialect: com.miral.configuration.sqllite.SQLLiteDialect
jpa:
  default:
    entity-scan:
      packages:
        - 'com.miral.products.dao.model'
        - 'com.miral.user.dao.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: com.miral.configuration.sqllite.SQLLiteDialect


